### ISSUE TITLE
Needed specific component ? post Here!

### ISSUE THREAD

**Issue by manolenso** [manolenso/intellij-foundation5#1]

**Comment by mspacemedia** [comment]
Hi Manolenso,

Just installed the latest version and 'zf-cprm' doesn't appear to be working? 

However 'zf-cpm' is working - do the docs need updating or the live-template?

Regards,
M

**Comment by manolenso** [comment]
Hi mspacemedia, 
I've just post 1.9 update for  correct the trigger name accorded to the doc: zf-cprm for Reveal Modal
thank 
Regards,
Manolenso
