### ISSUE TITLE
ADDinput not clearing after generating code

### ISSUE THREAD

**Issue by digitalredefined** [manolenso/intellij-foundation5#2]
When using the plugin in PHP Storm, I use ADDinput, ctrl=space and it generates the code but the ADDinput is appended to the end of it.  Otherwise seems to be running great.

Thanks!

**Comment by manolenso** [comment]
Hi, I had it myself this error with the last update 2.0, missing zf-nvib and associate ADDinput.
I'l post a new jar generated to correct this bug.
Thank for posting!

**Comment by digitalredefined** [comment]
No problem.  After I posted I started thinking twice about whether or not it was a bug.  If I were making more inputs it worked out great, I just kept re-using it to generate more.
